target-version = "py310"
line-length = 80
indent-width = 4

[lint]
# https://docs.astral.sh/ruff/rules/#legend
select = ["ALL"]
# D10* Missing docstring
ignore = [
    "D10",
    "D204",
    "D203",
    "D211",
    "D212",
    "D213",
    "EM101",
    "EM102",
    "ERA001",
    "FBT002",
    "FBT003",
    "FIX002",
    "PT001",
    "PT023",
    "Q001",
    "TD003",
    "TRY003",
    "COM812",
    "ISC001",
    "S603",
    "S607",
]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = '^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$'

[lint.flake8-quotes]
inline-quotes = "double"

[format]
quote-style = "double"
indent-style = "space"
docstring-code-format = false
