from __future__ import annotations

# ONC RPC (RFC 5531)
MSG_CALL = 0
MSG_REPLY = 1
MSG_ACCEPTED = 0

# Program numbers
PROG_MOUNT = 100005
PROG_NFS = 100003

MOUNT_VERSION = 3
NFS_VERSION = 3

# MOUNT procedures (RFC 1813, Appendix I)
MOUNTPROC_NULL = 0
MOUNTPROC_MNT = 1
MOUNTPROC_UMNT = 3

# NFSv3 procedures (RFC 1813)
NFSPROC_NULL = 0
NFSPROC_GETATTR = 1
NFSPROC_LOOKUP = 3
NFSPROC_ACCESS = 4
NFSPROC_READLINK = 5
NFSPROC_READ = 6
NFSPROC_READDIR = 16
NFSPROC_READDIRPLUS = 17
NFSPROC_FSSTAT = 18
NFSPROC_FSINFO = 19
NFSPROC_PATHCONF = 20

# NFSv3 status codes (nfsstat3)
NFS3_OK = 0
NFS3ERR_NOENT = 2
NFS3ERR_IO = 5
NFS3ERR_INVAL = 22

# ftype3
NF3REG = 1
NF3DIR = 2
NF3LNK = 5

FILE_HANDLE_SIZE = 8
COOKIE_VERF_SIZE = 8
