name: Python package

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build ruff mypy
        sudo apt install fuse3 libfuse3-dev libfuse-dev ffmpeg -y
        python -m pip install -e ".[lint]"
    - name: Test with pytest
      run: |
        python -m pip install -e ".[test]"
        pytest
    - name: Lint code with Ruff
      run: |
        ruff check --output-format=github
    - name: Check code formatting with Ruff
      run: |
        ruff format --diff
    - name: Lint code with mypy
      run: |
        mypy yandex_fuse
        mypy tests
    - name: Build package
      run: python -m build
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        generate_release_notes: true
        files: |
          dist/yandex_fuse-*.tar.gz
